- Makefile.am
- bench-heap.g
- gap/binaryheap.gd
- gap/binaryheap.gi
- init.g
- read.g
- src/binaryheap.c
- src/binaryheap.h
- src/datastructures.c
- tst/binaryheap.tst
This PR adds just the binary heap from PR #15. Things I'd like to do with it before merge (or after...)
* should its functions also get a `DT_` resp. `_DT_` prefix?
* when I wrote it, it was convenient to represent the heap as a record, as my prototype was written in GAP, which I then gradually converted to C. Perhaps we'd be better off rewriting this into a position object, though...
* There is a simple optimization I'd want to consider: if the user does not specify an `isLess`, or specifies `LT` resp. `\<`;  then detect that and do *not* invoke `CALL_2ARGS(isLess, ELM_PLIST(data, right), ELM_PLIST(data, left))`, instead use `LtFuncs`, for better performance.
* perhaps also use C++ templates for optimizations...?
* add an efficient _BinaryHeap_Create_C function which takes a list of …
> Adding a binary heap (WIP)

- src/hashfunctions.c
This lets clang produce considerably better code at -O3, as
it cannot tell that the initial TNUM_OBJ result can be reused.
> Tweak BasicPrimitiveHash to use switch/case

- gap/pairingheap.gi
- tst/heaptest.g
This PR fixes the merge-pairs function of pairing heaps to run in amortised `log n` instead of possibly quadratic time.
> Make Pairing Heap fast

- Makefile.am
- gap/pairingheap.gi
- src/datastructures.c
- src/datastructures.h
- src/hashmap.c
- src/pairingheap.c
- src/pairingheap.h
This speeds up the pairing heaps test by a factor of two. E.g.
on my system, I get these TestHeap timings:
Before this commit:
```
gap> Benchmark(function() TestHeap(PairingHeap); end, rec(minreps:=10));;
Performed 10 iterations, taking 4443 milliseconds.
average: 444.26 +/- 8.15 (+/- 2%)
median: 444.4478629827499
```
After this commit:
```
gap> Benchmark(function() TestHeap(PairingHeap); end, rec(minreps:=10));;
Performed 10 iterations, taking 1927 milliseconds.
average: 192.74 +/- 3.8 (+/- 2%)
median: 192.5236003994942
```
For reference:
```
Benchmark(function() TestHeap(BinaryHeap); end, rec(minreps:=10));;
Performed 10 iterations, taking 1534 milliseconds.
average: 153.41 +/- 5.09 (+/- 3%)
median: 153.8257709443569
```
> Reimplement merge_pairs in C

- src/hashfunctions.c
This has become necessary after commit 25165188 to the GAP git
repository
> Turn IS_PREC_REP into IS_PREC

- gap/hashset.gd
- gap/hashset.gi
- init.g
- read.g
- src/hashmap.c
- tst/hashmap.tst
- tst/hashset.tst
This reuses code from HashMap, but does not store values associated to keys, and provides a slightly different interface, in terms of AddSet, RemoveSet and \in.
In the future, we could also add methods for things like `UniteSet`, `Union`, `Intersection` etc. *should we want to*. Perhaps also a constructor to convert an ordered (GAP) set into a hash set.
> Add HashSet

- gap/binaryheap.gi
- gap/hashmap.gi
- gap/pairingheap.gi
- gap/plistdeque.gi
- gap/stack.gi
This works better with the Jupyter kernel and any future implementation
of printing/viewing.
Since these ViewStrings are fairly short there is also no harm in
producing the string before printing.
> Install ViewString instead of ViewObj

- src/hashfunctions.c
The shape of the bag containing a permutation has changed in GAP due to
the caching of the inverses introduced recently by Steve Linton. This
commit updates the hashing of permutations in datastructures so that it
works again. Resolves Issue #80.
> hash: fix hashing of permutations

- src/hashmap.c
- tst/hashmap.tst
- tst/hashset.tst
The requirement checks for inputs to hashset and hashmap functions used to test the type of the input object, which is incorrect, they should be testing the representation of the input object.
This lead to problems when the user or GAP made HashMaps or HashSets immutable, because that changes their type, and no functions for them work anymore.
> Fix input checks and mutability issues

- gap/hashmap.gi
- gap/union-find.gd
- src/hashmap.c
- tst/hashmap.tst
This isn't really documented, because I wasn't really sure where to document it, and we didn't document the old behaviour before anyway.
Also contains two tiny comment fixes.
> Make Immutable copy of keys in Hashed containers

- src/hashfunctions.c
- tst/hashfunctions/recursive.tst
The old hash function required calling SortPRecRNam, and also
would be effected by how GAP mapped record keys to RNams, meaning
different GAP sessions could return different answers.
Switch to actually hashing the keys, and also using '+' to combine
the different key-value pairs, so the hash value is unaffected by
how GAP stores records.
I have tested manually that if I load GAP and define keys in different orders I get the same hash output, but I can't think how to sensibly add this to a test file.
> Change to a stable hash function for records

- gap/slice.gi
- tst/slice.tst
If all packages were loaded, the generic GAP library method for ViewString
was ranked higher than our custom method, which is now fixed. This fixes test failures as seen e.g. [here](https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master-staging/jobs/579543541).
Also add a ViewObj method matching the ViewString method.
> Add ViewObj for slices, fix ViewString rank

- README.md
However, first we should make sure that AppVeyor builds actually work... When I just checked, they were not actually enabled - huh? I fixed that now, and started a build, let's see if it passes.
> Show AppVeyor build status in README

- gap/ordered.gd
- gap/plistdeque.gd
Gap 4.10.2, at least, does not seem to have a label for IsPositionalObjectRep:
```
#W WARNING: non resolved reference: rec(
BookName := "Ref",
Filt := "IsPositionalObjectRep" )
```
Given the referring text, a reference to the enclosing section seems more appropriate anyway.
> Fix positional object reference.

- src/hashfunctions.c
This fixes loading workspaces which use datastructures.
> Move InitHandlerFunc uses to InitKernel

- .appveyor.yml
- .gitignore
- Makefile.gappkg
- Makefile.in
- configure
This updates the buildsystem and factors out code shared with other packages into a new file `Makefile.gappkg`, in the hope that this will make it easier to share bugfixes and improvements between packages. (And perhaps in the future we can bundle this file with GAP itself?)
> Improve buildsystem, use shared Makefile.gappkg

- src/hashfunctions.c
My compiler (OS X Catalina) needs this include
> Add #include of stdlib.h in hashfunctions.c to get declaration of labs.

- gap/hashmap.gd
- gap/hashmap.gi
- gap/hashset.gd
- gap/hashset.gi
- tst/hashmap.tst
- tst/hashset.tst
This fixes two irritations I had with HashMap and HashSet.
(1) You can now give an initial value, as `HashSet([1,2,3])`, or `HashMap([ [1,2], [3,4] ])` (the hashmap notation is less nice, but I didn't have a nicer one).
(2) The printing of hashsets and hashmaps now prints their values -- it actually prints out this notation, so it can be used to later read them back in.
> Add printing and initial value to HashMap and HashSet

- src/hashmap.c
For better compatibility with future GAP releases
> Switch src/compiled.h to compiled.h

- src/hashfunctions.c
This is a bad idea in many applications
> Don't use identity as hash func for small ints

- src/hashfunctions.c
- src/hashfunctions.h
- tst/hashfunctions/recursive.tst
As in title, fixes a bug where rec(1:=2,3:=4) and rec(1:=4,2:=3) had the same hash.
Add some tests that make sure a selection of basic objects don't have hash collisions (obviously these could still hypothetically collide by extremely bad luck, but they do not).
> Make sure rec(1:=2,3:=4) and rec(1:=4,2:=3) have different hashes
