tst/basictests/queue.tst, tst/testall.g
=> Rearrange tests

tst/basictests/avl.tst
Add some basic tests for AVL trees.
=> Add AVL Tests

gap/binaryheap.gd, gap/binaryheap.gi, gap/heap.gd, gap/heap.gi, gap/pairingheap.gi, init.g, read.g, src/binaryheap.c, tst/heap.tst
This PR does a couple of things (and hence might need breaking up into multiple PRs):
* It converts the record based binary heaps into positional objects
* It ties binary heaps into the defined API using `Push`, `Pop` and `Peek`
* It adds and runs some basic tests on the two heap implementations that we have
* It fixes a few subtle bugs that were either introduced by over-eager merging or were there all along.
=> Binary heap work

Makefile.am, gap/hashfunctions.gd, gap/hashfunctions.gi, init.g, read.g, src/datastructures.c, src/hashfunctions.c, src/hashfunctions.h, tst/hashfunctions/hashtestfuncs.g, tst/hashfunctions/int.tst, tst/hashfunctions/perm.tst, tst/hashfunctions/permgroup.tst, tst/hashfunctions/pperm.tst, tst/hashfunctions/recursive.tst, tst/hashfunctions/string.tst, tst/hashfunctions/trans.tst
This adds hash functions for most built-in types, and also
permutation groups.
=> Add simple hash functions for some GAP types

.travis.yml, scripts/build_gap.sh, scripts/build_pkg.sh, src/hashfunctions.h, tst/hashmap.tst
- add a 32bit build
- add a build without optimizations
- only enable profiling for the package itself
=> Overhaul Travis setup

.travis.yml, src/hashfunctions.c, src/hashfunctions.h, tst/hashmap.tst
This patch is mainly just enough to make the 32-bit build actually succeed.
=> Small hashfuncs tweaks

gap/binaryheap.gi, gap/dllist.gd, gap/heap.gd, gap/lqueue.gi, gap/pairingheap.gi, gap/queue.gd, gap/stack.gd, gap/stack.gi
Also change Length to Size
Resolves #47
=> Remove IsCollection filter

gap/hashfunctions.gd, gap/hashfunctions.gi, src/hashfunctions.c, tst/hashfunctions/hashtestfuncs.g, tst/hashfunctions/int.tst, tst/hashfunctions/perm.tst, tst/hashfunctions/pperm.tst, tst/hashfunctions/recursive.tst, tst/hashfunctions/string.tst, tst/hashfunctions/trans.tst
Some general cleanups and improvements. Some also (shockingly) bad documentation, but I'm thinking something is better than nothing.
=> Further hash function improvements

gap/lqueue.gi, tst/plistqueue.tst
This is a vanity-PR to get test coverage up to 100% for `PlistQueue`
=> Test lqueue more

Makefile.am, gap/union-find.gd, gap/union-find.gi, gap/union-find2.gi, init.g, read.g, src/datastructures.c, src/uf.c, src/uf.h, tst/plistdeque.tst, tst/uf.tst
Not perfect yet (includes an implementation that requires the Bitfielfds PR and needs some more tidying and tests.
=> WIP Union Find

src/hashmap.c
If the hash value was negative, then the value perturb converged
to -1 (instead of 0). But then the perturbation map
idx -> (5 * idx + perturb + 1)  mod 2^N
degenerated to the linear function
idx -> (5 * idx )  mod (2^N-1)
which does not have maximal period when 5 divides 2^N-1, so
e.g. for N=4, N=8, ...
The fix consist in making pertub unsigned. And while we are at it,
we also make everything else unsigned for which negative values
make no sense (e.g. idx, capacity, mask, ...)
Fixes #83
=> Fix infinite loop in hashmap lookup

gap/hashmap.gd, gap/hashmap.gi, gap/hashset.gi, tst/hashmap.tst, tst/hashset.tst
Also add Set and AsSet methods for HashSet
Resolves #82
=> Add iterators for HashMap and HashSet

PackageInfo.g
=> Check availability of kernel module

gap/memoize.gd, gap/memoize.gi, init.g, read.g, tst/memoize.tst
This uses a hash table to memoize any function for which we can hash the inputs.
=> Add MemoizeFunction

PackageInfo.g, doc/Intros.autodoc, doc/datastructures.bib, doc/install.xml, doc/intro.xml, gap/avltree.gi, gap/binaryheap.gd, gap/binaryheap.gi, gap/hashfunctions.gd, gap/hashmap.gd, gap/hashmap.gi, gap/hashset.gd, gap/hashset.gi, gap/heap.gd, gap/memoize.gd, gap/ordered.gd, gap/ordered.gi, gap/pairingheap.gd, gap/pairingheap.gi, gap/plistdeque.gd, gap/plistdeque.gi, gap/queue.gd, gap/skiplist.gi, gap/stack.gd, gap/stack.gi, gap/union-find.gi, gap/union-find2.gi, makedoc.g, tst/plistdeque.tst, tst/stack.tst
This is work-in-progress, so do not merge yet.
=> A stab at a more comprehensive documentation

src/hashfunctions.c
=> Add cookies to hash function handlers

gap/slice.gd, gap/slice.gi, init.g, read.g, tst/slice.tst
=> Add Slices (again)

tst/hashfunctions/recursive.tst, tst/hashmap.tst
=> Disable a test with diffs between GAP 4.10 and 4.11

gap/heap.gd, gap/ordered.gd, gap/queue.gd
=> doc: fix some refs and other minor issues

.github/workflows/CI.yml, PackageInfo.g, src/avl.c, src/binaryheap.c, src/datastructures.h, src/hashfunctions.c, src/hashmap.c, src/pairingheap.c, src/skiplist.c, src/uf.c
=> Replace GVARFUNC by GAP's GVAR_FUNC_*ARGS macros

src/binaryheap.c, src/datastructures.c, src/datastructures.h, src/hashmap.c, src/pairingheap.c
No functional change for this package but makes it future-proof.
=> Replace compiled.h by gap_all.h
